os:
  - linux
  - osx

env:
  - VERSION=5.2.7.2
  - VERSION=5.3.7.2
  - VERSION=5.4.7.2
  - VERSION=6.0.7.3
  - VERSION=6.1.5.2

language: generic

# On Mac OS X, only test selected versions (the oldest and a few recent versions).
# If they work, reasonably everything else does as well.
# We do this because testing Mac OS X on Travis is painfully slow.
matrix:
  include:
    - os: osx
      env: VERSION=6.1.5.2
    - os: osx
      env: VERSION=5.4.7.2
  exclude:
    - os: osx

before_install:
  - sudo VERSION=$VERSION bash ci/linux.bash
  - sudo VERSION=$VERSION bash ci/osx.bash

script:
  - make -C tests
